name: Python package
name: Python package
 
on:
on:
  push:
  push:
    branches: ["main"]
    branches: [ "main" ]
  pull_request:
  pull_request:
    branches: ["main"]
    branches: [ "main" ]
 
jobs:
jobs:
  build:
  build:
    runs-on: ubuntu-latest
    runs-on: ubuntu-latest
 
    strategy:
    strategy:
      fail-fast: false
      fail-fast: false
      matrix:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        python-version: ["3.9", "3.10", "3.11"]
 
    steps:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
 
      - name: Set up Python ${{ matrix.python-version }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        uses: actions/setup-python@v3
        with:
        with:
          python-version: ${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}
 
      - name: Install dependencies
      - name: Install dependencies
        run: |
        run: |
         python -m pip install --upgrade pip
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          python -m pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
      - name: Lint with flake8
      - name: Lint with flake8
        run: |
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
 
      - name: Test with pytest
      - name: Test with pytest
        run: |
        run: |
          pytest
